### PR TITLE
Add url base config option

### PR DESCRIPTION
**Pull request by liaralabs**

### CODE REVIEW

**Comment by flying-sausages** [comment]
oh SHIT wadup

**Comment by flying-sausages** [comment]
It works! We'll just have to figure out some deployment things now.

I get this when I visit a non-panel baseurl, which we might need to make changes in the nginx config for.
image

If we're gonna let people use this, then we need to write the appropriate documentation for it and think of how we'd like to expose this during installation, and how we want to let people change this after panel has already been deployed.

**Comment by liaralabs** [comment]
> I get this when I visit a non-panel baseurl, which we might need to make changes in the nginx config for.

This is to be expected. The URL path needs to be appended to the location in the nginx blocks -- standard base url stuff.

> If we're gonna let people use this, then we need to write the appropriate documentation for it and think of how we'd like to expose this during installation, and how we want to let people change this after panel has already been deployed.

The only documentation I intend to provide is listing the `URLBASE` config option on the Panel docs. Using the panel in a way that was not intended is not something that is supported nor am I interested in putting support in the main scripts or writing loads of documentation on helping users do unsupported things. The only people asking for this have been coming with knowledge and looking for the specific option that will allow them to move the panel to a new base.

In fact I seem to remember a discord conversation of which the gist was: "add the option, list the docs and forget about it".

**Comment by flying-sausages** [comment]
Fair, sounds good to me. I'd still add a comment into `update/panel.sh` for whoever will be the next person who will want to make changes to the nginx config.

**Comment by liaralabs** [comment]
I don't follow what you mean by adding a comment. Adding an echo? How do we determine when to display it -- this isn't something I want to show every time the panel is updated.

**Comment by flying-sausages** [comment]
> I don't follow what you mean by adding a comment. Adding an echo? How do we determine when to display it -- this isn't something I want to show every time the panel is updated.

No, literally a comment in the code like
```bash
cd
rm -rf /
# Do not touch the location block for panel yo
```

**Pull request merged**
